on:
  schedule:
    - cron: '15 2 * * *'
  workflow_dispatch: {}

jobs:
  trigger-deployment:
    name: Trigger Cloudflare deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Post to Cloudflare Pages Deploy Hook
        run: curl -X POST "${{ secrets.CLOUDFLARE_API_URL }}"